### ISSUE TITLE
Kotna hitrost animacije "črte"

### ISSUE THREAD

**Issue by markbaltic** [markbaltic/AnimacijaMuzike#1]
g.drawLine sprejme v argumente le int. Torej kotna hitrost (s katero se riše stanje črte - iluzija premikanja) ne more bit manjša od 1.

**Comment by bbYYJnhA** [comment]
V mainu bi rad spreminjal kotno hitrost. Sem dodal komentar v komit kje točno.

**Comment by markbaltic** [comment]
Sem dodal spremenljivko kotnahitrost, preko katere lahko iz Test komuniciraš v Animacija. Pomagalo bi, če mi poveš, KAKO bi rad spreminjal kotno hitrost (ji podajal direkt velikost hitrosti, ji prišteval/odšteval od trenutne)... Prav tako je pomembno kako VELIKI intigerji bodo te spremembe. Ker večji kot so, bolj morava razdelit ravnino na kroge (premenljivka n v animaciji - se za črte in kroge posebej definira, ko izbereš obliko animacje v meniju...). Če sem napisal nerazumljivo me kar pokliči :D
